### ISSUE TITLE
plugin_name

### ISSUE THREAD

**Issue by baskettcase** [Tmeister/wppb-gen-site#1]
the private variable in each class $plugin_name shouldn't be changed to the plugin name should it? That should stay $plugin_name. It's the only problem that I've found with your generator so far. Thank you for that tool! :)

Im not sure if it's desirable, but do you think there could be a version that didn't have the plugin name in the file name? so for example instead of class.plugin_name.activator.php you could have a switch that names the files class.activator.php?

**Comment by Tmeister** [comment]
Yeah, You are right.

I will fix this asap.

Thanks for the update.
