### ISSUE TITLE
Advanced option for coding styles [enhancement]

### ISSUE THREAD

**Issue by rvarbanov** [Tmeister/wppb-gen-site#11]
Hi, 

I want to suggest an advanced option for the generator. One that will allow developers to chose coding styles. For example the pluging currently outputs the code with spaces like this:

```
if ( ! defined( 'WPINC' ) ) {
    die;
}
```

I would love to see an option to convert that code to:

```
if(!defined('WPINC')) {
    die;
}
```

P.S. I love your WP Plugin generator! I even bookmarked it!

**Comment by JKetelaar** [comment]
If you follow the WordPress coding standards, this [shouldn't](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage) happen

**Comment by rvarbanov** [comment]
Thank you for the link.
