### ISSUE TITLE
[Feature Request] Custom boilerplate fork

### ISSUE THREAD

**Issue by timersys** [Tmeister/wppb-gen-site#12]
Hi , would be great if we can provide a custom fork of the plugin. So I can use the power of your app with all the default changes I use on my own boilerplate fork.

Something like adding https://github.com/timersys/WordPress-Plugin-Boilerplate to use that instead of default one

Thanks

**Comment by Tmeister** [comment]
I think the best way to handle this is fork the project and change the repo in the source code, I'm pretty sure that 99.9% will not use that option.
