### ISSUE TITLE
Change coming for the boilerplate

### ISSUE THREAD

**Issue by DevinVinson** [Tmeister/wppb-gen-site#8]
I'm not sure if this will impact the generator or not: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/295

If so, let me know and we can coordinate a specific time for the change.

**Comment by Tmeister** [comment]
Yes, there is some lines that reference to the **trunk** folder, would be great to have a new development branch with the new folder structure in order to test the changes in the generator.

When is your ETA?

Thanks for the heads-up!!

**Comment by DevinVinson** [comment]
I'll try and get a new branch up today. I'd love to have it all done before Sunday as I'm going to reference the boilerplate and your generator at a talk.

**Comment by DevinVinson** [comment]
Quite a bit later than I would have liked but I've got the update pushing out in a moment.

**Comment by DevinVinson** [comment]
Looks like the code won't be refreshed for a few hours. I'll see if I can pull your repo down and test locally since its pretty last minute.

**Comment by Tmeister** [comment]
Done, the change is ready and live.

http://wppb.me/ is serving a zip file with the new folder structure.
