### ISSUE TITLE
WPPB versions

### ISSUE THREAD

**Issue by codecowboy** [Tmeister/wppb-gen-site#9]
What version or branch of the WPPB does the generator use? Does the http://wppb.me/ site always use the same version?

**Comment by Tmeister** [comment]
Hi,

http://wppb.me automatically pull the code from https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/tree/master every day, so the code used in the generator is fresh ;).

You can see the code here 

https://github.com/Tmeister/wppb-gen-site/blob/master/server.js#L259-L267
